myapp/config/routes.rb
Rails.application.routes.draw do
root 'collections#index'  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

get 'collections/index'

resources :collections do
    member do
        get :delete
    end
end
# collection do
# get :{insert name}
# end                        

end

myapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myapp/app/models/book.rb
class Book < ApplicationRecord
    # def add
    # end
    # def remove
    # end
    
end

myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

myapp/app/controllers/book_collection_controller.rb
class BookCollectionsController < ApplicationController
    #CRUD CREATE READ UPDATE DESTROY

    def create
        @book = Book.new(book_params)

        if @book.save

            redirect_to('book_collection/index')
        else 
            render('new')
        end
    end
    
    def new
        @book = Book.new
    end

    def show
        @book = Book.find(params[{'id' => 'index'}])
    end

    def index
        @books = Book.order('price ASC')
    end

    def update
    end

    def edit
    end

    def delete
    end

    def destroy
    end
end

myapp/app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
    #CRUD CREATE READ UPDATE DESTROY

    def create
        @book = Book.new(book_params)

        if @book.save
            redirect_to(collections_path)
            flash.alert = "Created Book."

        else 
            render('new')
        end        
    end
    
    def new
        @book = Book.new
    end

    def show
        @book = Book.find(params[:id]) 
        flash.alert = "Showed Book."

    end

    def index
        @books = Book.order('price ASC')
    end

    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            redirect_to(collections_path)
            flash.alert = "Edited Book."

        else
            render('edit')
        end
    end

    def edit
        @book = Book.find(params[:id])
    end

    def delete
        @book = Book.find(params[:id])
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to(collections_path)
        flash.alert = "Deleted Book."
    end

private

    def book_params
      params.require(:book).permit(:title, :author, :genre, :price, :published_date)
    end

end

myapp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp/app/helpers/book_collection_helper.rb
module BookCollectionHelper
end

myapp/app/helpers/collection_helper.rb
module CollectionHelper
end

myapp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

myapp/app/views/collections/_form.html.erb
<table summary="Subject form fields">
  <tr>
    <th>Title</th>
    <td><%= f.text_field(:title) %></td>
  </tr>
  <tr>
    <th>Author</th>
    <td><%= f.text_field(:author) %></td>
  </tr>
  <tr>
    <th>Genre</th>
    <td><%= f.text_field(:genre) %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= f.text_field(:price) %></td>
  </tr>
  <tr>
    <th>Published Date</th>
    <td><%= f.text_field(:published_date) %></td>
  </tr>

</table>

myapp/app/views/collections/create.html.erb
<%= form_for(@book) do |f| %>
    <%= f.text_field(:name) %>
    <%= f.text_field(:author) %>
    <%= f.text_field(:genre) %>
    <%= f.text_field(:price) %>
    <%= f.text_field(:published_date) %>

    <%= f.submit ("Submit Book") %>
<% end %>

myapp/app/views/collections/delete.html.erb
<%= link_to("<<< Return back to Collection", collections_path, :class => 'back-link') %>
  <div class="book delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, url: collection_path, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this page?</p>
    <p><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>
</div>

myapp/app/views/collections/destroy.html.erb
<%= link_to("<<< Return back to Collection", collections_path, :class => 'back-link') %>
<div class="book new">
  <h2>Create Book</h2>

  <%= form_for(@book, url: collections_path) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

myapp/app/views/collections/edit.html.erb
<%= link_to("<<< Return back to Collection", collections_path, :class => 'back-link') %>
<div class="book update">
  <h2>Edit Book</h2>

  <%= form_for(@book,  url: collection_path) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Book") %>
    </div>


  <% end %>
</div>

myapp/app/views/collections/index.html.erb
<div class="books index">
  <h2>Book Collection</h2>

  <%= link_to("Add", new_collection_path, :class => 'action new') %>

  <table class="listing" summary="book list">
    <tr class="header">
      <th>Book</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Price</th>
      <th>Published Date</th>
      <th>Actions</th>
    </tr>
    <% if @books.nil? 
    else
     @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author %></td>
      <td><%= book.genre %></td>
      <td class="center"><%= book.price %></td>
      <td class="center"><%= book.published_date %></td>
      <td class="actions">
        <%= link_to("Show", collection_path(book), :class => 'action show') %>
        <%= link_to("Edit", edit_collection_path(book), :class => 'action edit') %>
        <%= link_to("Delete", delete_collection_path(book), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
    <tr>
    <td>Previous Action:
    <%=  flash.alert %>
    </td>
    </tr>
    <% end %>
  </table>

</div>

myapp/app/views/collections/new.html.erb
<%= link_to("<<< Return back to Collection", collections_path, :class => 'back-link') %>
<div class="book new">
  <h2>Create Book</h2>

  <%= form_for(@book, url: collections_path) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create") %>
    </div>

  <% end %>
</div>

myapp/app/views/collections/show.html.erb
<%= link_to("<< Back to List", collections_path, :class => 'back-link') %>

<div class="books show">
  <h2>Show Book</h2>

  <table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @book.genre%></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td><%= @book.published_date %></td>
    </tr>
  </table>

</div>

myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

myapp/app/views/welcome/index.html.erb
<h2>Welcome to the Book Collection</h2>

<p><%= link_to('Add Book', {:controller => 'book_collection', :action => 'new'}) %>


<p>
    The time is now: <%= Time.now %>
</p>